{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyO+cD/El++XMRE/LPJZkbPZ"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"sFBgmVO9amK3","executionInfo":{"status":"ok","timestamp":1712005001906,"user_tz":-120,"elapsed":10245,"user":{"displayName":"Jiří Sladký","userId":"09302576644665798665"}},"outputId":"5a60e2e3-ae9d-4a1e-e459-26c6a8ff85e3"},"outputs":[{"output_type":"stream","name":"stdout","text":["fatal: destination path 'photo_backuper' already exists and is not an empty directory.\n","/content/photo_backuper\n","Obtaining file:///content/photo_backuper/photo_backuper\n","  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Requirement already satisfied: send2trash>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from photo-backuper==0.1) (1.8.2)\n","Installing collected packages: photo-backuper\n","  Running setup.py develop for photo-backuper\n","Successfully installed photo-backuper-0.1\n"]}],"source":["# clone repo and install photo_backuper package\n","!git clone https://github.com/jirslad/photo_backuper.git\n","%cd photo_backuper\n","%pip install -e photo_backuper"]},{"cell_type":"code","source":["# run demo\n","!python main.py --demo --mode new_folders --utility_root data/IMAGES/source --source_folder data/IMAGES/source --target_folder data/IMAGES/target"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"0Vxi-sGXblBn","executionInfo":{"status":"ok","timestamp":1712005002392,"user_tz":-120,"elapsed":494,"user":{"displayName":"Jiří Sladký","userId":"09302576644665798665"}},"outputId":"e6097271-20a1-4ba2-c8c0-0dea29b4f3a6"},"execution_count":2,"outputs":[{"output_type":"stream","name":"stdout","text":["usage: main.py [-h] [--mode {initialize,new_folders,modified_folders}] --utility_root UTILITY_ROOT\n","               [--source_folder SOURCE_FOLDER] [--target_folder TARGET_FOLDER]\n","main.py: error: unrecognized arguments: --demo\n"]}]}]}